//! Hermes Mobile — Tauri v2 entrypoint (shared by desktop dev and the Android
//! target). `run()` is the mobile entry point; the Android project generated by
//! `tauri android init` calls into it. Step 2 registers the transport commands
//! (`rest_request`, `gateway_connect`, `gateway_request`, `gateway_close`) here.

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .run(tauri::generate_context!())
        .expect("error while running Hermes Mobile");
}
