//! Hermes Mobile — Tauri v2 entrypoint (shared by desktop dev and the Android
//! target). `run()` is the mobile entry point; the Android project generated by
//! `tauri android init` calls into it.
//!
//! All network traffic runs in Rust (`transport`), not the webview — see
//! `transport.rs`. The frontend drives it over IPC and reuses the JS
//! `JsonRpcGatewayClient` via an IPC-backed WebSocket.

mod transport;

use transport::{http_request, ws_close, ws_open, ws_send, TransportState};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_os::init())
        .manage(TransportState::new())
        .invoke_handler(tauri::generate_handler![
            http_request,
            ws_open,
            ws_send,
            ws_close
        ])
        .run(tauri::generate_context!())
        .expect("error while running Hermes Mobile");
}
