//! Hermes Universal — Tauri v2 entrypoint (shared by desktop dev and the mobile
//! Android/iOS targets). `run()` is the mobile entry point; the Android project
//! generated by `tauri android init` calls into it.
//!
//! All network traffic runs in Rust (`transport`), not the webview — see
//! `transport.rs`. The frontend drives it over IPC and reuses the JS
//! `JsonRpcGatewayClient` via an IPC-backed WebSocket.
//!
//! (Android note: the generated `RustWebView.getCookies` is patched null-safe by
//! `gen/android/buildSrc/.../BuildTask.kt` to avoid a wry 0.55 crash on cookie
//! polling — see that file.)

mod active_work;
mod ambient;
mod app_log;
mod app_state;
mod appearance;
mod artifact;
#[cfg(desktop)]
mod backend_log;
mod background;
mod browser;
mod chat_onboarding;
mod cloud;
mod composer_paste;
mod connections;
mod context_menu;
mod data_url_read_max;
mod deep_link;
#[cfg(desktop)]
mod external_terminal;
mod favicon;
mod files;
mod find_in_page;
#[cfg(desktop)]
mod fs_ipc;
mod git_review;
mod git_worktree;
mod host_facts;
mod hud;
#[cfg(desktop)]
mod hud_modifier;
mod intro_reveal;
mod keep_awake;
mod link_title;
mod local_backend;
mod local_install;
mod marketplace;
mod mcp_oauth;
mod media;
mod oauth;
mod pet_overlay;
mod plugins;
mod plugins_install;
#[cfg(desktop)]
mod preview_capture;
mod profile_default;
mod pty;
mod quick_entry;
mod repo_scan;
#[cfg(desktop)]
mod screenshot;
mod secrets;
mod shortcuts;
mod ssh;
mod surface;
mod telemetry;
mod transport;
mod tray;
mod tunnels;
mod updates;
mod voice;
#[cfg(desktop)]
mod watchers;
mod webview_cookies;
mod window;
#[cfg(desktop)]
mod workspace;

use active_work::{set_active_work, ActiveWorkState};
use ambient::{claim_ambient_cue, AmbientState};
use app_log::{logs_recent, logs_reveal, logs_root, report_renderer_error, AppLogState};
use app_state::{get_app_flag, set_app_flag};
use appearance::{appearance_capabilities, appearance_set_glass, AppearanceState};
use artifact::{artifact_release, artifact_stage, ArtifactState, ARTIFACT_SCHEME};
use background::{get_background_mode, quit_app, set_background_mode, BackgroundState};
use browser::commands::{
    browser_back, browser_capabilities, browser_clear_data, browser_close, browser_eval,
    browser_forward, browser_navigate, browser_open, browser_open_devtools, browser_reach_reset,
    browser_reach_url, browser_reload, browser_set_bounds, browser_set_visible, browser_stop,
};
use browser::BrowserState;
use chat_onboarding::{chat_onboarding_grow, chat_onboarding_solo_boot};
use cloud::{
    portal_agent_sign_in, portal_discover_agents, portal_login, portal_logout, portal_status,
};
use composer_paste::{save_clipboard_image, save_image_buffer, save_pasted_text};
use connections::managed_update::{connections_update_managed, ManagedUpdateGate};
use connections::{
    connections_claim_resume, connections_commit_source, connections_current_source,
    connections_list, connections_migrate, connections_remove, connections_resolve,
    connections_roster, connections_save, connections_set_last_used, connections_set_launch_mode,
    connections_set_primary, connections_test, connections_update_all, ConnectionsState,
};
use context_menu::{
    context_menu_copy_image, context_menu_install, context_menu_save_image,
    context_menu_set_suppressed, ContextMenuState,
};
use data_url_read_max::{
    read_capped_file_base64, read_capped_file_base64_for_attach, set_data_url_read_max,
    DataUrlReadMaxState,
};
use deep_link::{deep_link_ready, DeepLinkState};
#[cfg(desktop)]
use external_terminal::{open_in_terminal, open_session_in_terminal};
use favicon::{resolve_favicon, FaviconState};
use files::{cancel_download, download_file, download_folder, DownloadState};
use find_in_page::{find_in_page, stop_find_in_page};
#[cfg(desktop)]
use fs_ipc::{fs_git_root, fs_open_dir, fs_read_dir, fs_rename, fs_trash, fs_write_text};
use git_review::{
    git_file_diff, git_repo_status, git_review_commit, git_review_commit_context,
    git_review_create_pr, git_review_diff, git_review_list, git_review_pr_list, git_review_push,
    git_review_rev_parse, git_review_revert, git_review_ship_info, git_review_stage,
    git_review_unstage,
};
use git_worktree::{
    git_base_branch_list, git_branch_list, git_branch_switch, git_worktree_add, git_worktree_list,
    git_worktree_remove,
};
use host_facts::{get_machine_profile, get_on_battery, get_remote_display_reason, HostFactsState};
use hud::{
    hud_begin_move, hud_broadcast_changed, hud_emit_goto, hud_end_move, hud_move_by,
    hud_reset_layout, hud_set_bounds, hud_set_ignore_mouse, hud_set_session,
    hud_set_workspace_transfer, hud_windowing, HudState,
};
#[cfg(desktop)]
use hud_modifier::{
    hud_modifier_open_permission, hud_modifier_settings_get, hud_modifier_settings_set,
    HudModifierStateHandle,
};
use intro_reveal::{
    intro_reveal_close, intro_reveal_open, intro_reveal_ready, intro_reveal_skip, IntroRevealState,
};
use keep_awake::{set_keep_awake, KeepAwakeState};
use link_title::fetch_link_title;
use local_backend::{
    local_backend_kill, local_backend_restart, local_backend_spawn, local_backend_status,
    local_backend_stop, LocalBackendState,
};
use local_install::{local_install_cancel, local_install_detect, local_install_start};
use marketplace::{marketplace_fetch, marketplace_search};
use mcp_oauth::{mcp_oauth_cancel, mcp_oauth_listen, mcp_oauth_wait, McpOauthState};
use media::{media_set_target, MediaState, MEDIA_SCHEME};
use oauth::{oauth_login, oauth_logout, oauth_status};
use pet_overlay::{
    pet_overlay_close, pet_overlay_control, pet_overlay_open, pet_overlay_push_state,
    pet_overlay_set_bounds, pet_overlay_set_focusable, pet_overlay_set_ignore_mouse,
};
use plugins::{plugins_list, plugins_read, plugins_root};
use plugins_install::{plugins_install_desktop, plugins_probe, plugins_remove_desktop};
#[cfg(desktop)]
use preview_capture::capture_preview;
use profile_default::{profile_default_get, profile_default_set};
use pty::{pty_kill, pty_resize, pty_spawn, pty_write, PtyState};
use quick_entry::{quick_entry_settings_get, quick_entry_settings_set, QuickEntryState};
use repo_scan::repo_scan_git_repos;
#[cfg(desktop)]
use screenshot::{
    screenshot_capture, screenshot_open_permission, screenshot_settings_get,
    screenshot_settings_set, screenshot_subscribe, ScreenshotStateHandle,
};
use secrets::{
    secrets_clear, secrets_delete, secrets_get, secrets_lock, secrets_set, secrets_status,
    secrets_unlock,
};
use shortcuts::{global_shortcut_take_pending, global_shortcuts_sync, ShortcutState};
use ssh::{
    ssh_answer_prompt, ssh_cancel, ssh_connect, ssh_disconnect, ssh_install, ssh_list_config_hosts,
    ssh_resolve_host, ssh_test, ssh_trust_host_key, SshState,
};
use surface::below::read_window_below;
use surface::{surface_capabilities, surface_set_interactive_rect};
use transport::{
    cookies_clear, cookies_export, cookies_import, http_request, ws_close, ws_open, ws_send,
    TransportState,
};
use tray::{tray_set_labels, tray_set_status, TrayState};
use updates::{relaunch_app, update_check, update_install, update_open_download, UpdateState};
use voice::{
    voice_arm, voice_close, voice_force_turn, voice_open, voice_suspend, voice_update_auth,
    voice_wake_listen, VoiceState,
};
#[cfg(desktop)]
use watchers::{stop_preview_file_watch, watch_directory, watch_preview_file, WatchersState};
use window::{
    close_this_window, hide_satellite_window, hide_this_window, is_satellite_window_visible,
    open_browser_window, open_instance_window, open_satellite_window, open_screen_window,
    open_session_window, open_tile_window, resize_satellite_window, show_app_window,
};
#[cfg(desktop)]
use workspace::{normalize_preview_target, read_file_text, sanitize_workspace_cwd};

/// Open a URL in the system browser. Routed through the opener plugin's Rust API
/// rather than its JS `openUrl` command: a Rust-internal call isn't gated by the
/// opener ACL/scope (which was silently blocking the JS path), so provider OAuth
/// sign-in and docs links reliably launch the OS browser.
#[tauri::command]
fn open_external(app: tauri::AppHandle, url: String) -> Result<(), String> {
    use tauri_plugin_opener::OpenerExt;
    app.opener()
        .open_url(url, None::<&str>)
        .map_err(|e| e.to_string())
}

/// The same handoff, callable from Rust.
///
/// `open_external` itself cannot be made `pub(crate)`: `#[tauri::command]`
/// re-exports its generated `__cmd__*` macros at the visibility of the function
/// it decorates, and two definitions of that macro in one module do not
/// compile. The in-app browser's navigation guard needs this door for a
/// `mailto:`, a refused `window.open`, and a download it will not take.
pub(crate) fn open_url_externally(app: &tauri::AppHandle, url: &str) {
    use tauri_plugin_opener::OpenerExt;

    if let Err(err) = app.opener().open_url(url, None::<&str>) {
        log::warn!("could not hand a url to the system browser: {err}");
    }
}

/// Reveal a path in the OS file manager (Finder/Explorer/Files), selecting the
/// item. Routed through the opener plugin's Rust API — like `open_external`, a
/// Rust-internal call isn't gated by the opener ACL/scope. Desktop-local only:
/// the caller must ensure the path exists on this machine's disk.
#[tauri::command]
fn reveal_in_file_manager(app: tauri::AppHandle, path: String) -> Result<(), String> {
    use tauri_plugin_opener::OpenerExt;
    app.opener()
        .reveal_item_in_dir(path)
        .map_err(|e| e.to_string())
}

/// Should a window losing focus end the credential unlock?
///
/// Normally yes — that is the whole point of the lease. The exception is an
/// interactive sign-in, which defocuses the app BY DESIGN: the desktop cookie flow
/// opens its own `hermes-oauth` window over the app, the portal flow opens
/// `hermes-portal`, and the RFC 8252 flow hands the login to the system browser and
/// backgrounds us entirely. All three used to slam the gate shut at the exact moment
/// the flow needs it open, and every gated `secrets_get` for the rest of the sign-in —
/// the cookie jar, the saved token — then failed with `locked`.
///
/// Two signals, because neither covers the other. The lease
/// (`oauth::sign_in_active`) spans the whole command including the system-browser arm,
/// where no window of ours exists to match on. The labels cover the moment a sign-in
/// window itself loses focus, which can outlive the lease by a beat while the window
/// is torn down.
fn defocus_ends_the_lease(label: &str) -> bool {
    if oauth::sign_in_active() {
        return false;
    }

    !matches!(
        label,
        oauth::OAUTH_WINDOW_LABEL | cloud::PORTAL_WINDOW_LABEL
    )
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Route Rust `log::` output somewhere a person can read it on mobile (tao
    // doesn't reliably install a logger, so diagnostics were invisible).
    #[cfg(target_os = "android")]
    android_logger::init_once(
        android_logger::Config::default()
            .with_max_level(log::LevelFilter::Info)
            .with_tag("hermes"),
    );

    // The iOS half, added because its absence hid a real bug for a whole debugging
    // session: an ATS-blocked sign-in navigation is reported ONLY as a `log::error!`
    // from inside wry's event loop, and with no logger installed that line — and
    // every `[oauth]`/`[portal]` breadcrumb next to it — went nowhere. The symptom
    // was "the button does nothing", with no way to tell a refused navigation from a
    // command that never ran.
    //
    // Deliberately fire-and-forget, exactly like `init_once` above: `telemetry::init`
    // below may install `tracing_log::LogTracer` as the global logger first, and
    // losing that race must cost us a log sink, never the app. (This is also why the
    // richer `tauri-plugin-log` is not used here — it installs its logger from plugin
    // setup and turns the same race into a failed build.)
    // The subsystem is the iOS bundle identifier (tauri.conf.json `identifier`), so
    // `log stream --predicate 'subsystem == "com.jaxmatrix.mjx-unofficial-hermes"'`
    // filters to just this app. Note the hyphens — the Android namespace above spells
    // the same id with underscores, and only this form matches the iOS bundle.
    #[cfg(target_os = "ios")]
    let _ = oslog::OsLogger::new("com.jaxmatrix.mjx-unofficial-hermes")
        .level_filter(log::LevelFilter::Info)
        .init();

    // The desktop half, and the last platform to get one. Its absence hid the macOS
    // keychain failure completely: `store_native_tokens` could not write, said so with
    // a `log::warn!`, and nothing on desktop consumed `log::` — so a sign-in that
    // finished and left the app signed out came with no diagnostic at all.
    //
    // Fire-and-forget for the same reason as the two above: `telemetry::init` may win
    // the race to install the global logger (tracing_log's LogTracer), and losing it
    // must cost a log sink, never the app. `try_init` (not `init`) is what makes that
    // true — `init` panics.
    //
    // RUST_LOG still wins when it is set; this only supplies the default.
    #[cfg(not(any(target_os = "android", target_os = "ios")))]
    let _ = env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info"))
        .try_init();

    // Span tracing. FIRST, so boot itself lands inside the trace rather than
    // before it. Compiled out entirely without `--features tracing`, and inert
    // even then unless HERMES_TRACE=1 — see telemetry.rs for why it is two
    // switches rather than one.
    telemetry::init();

    // Install a rustls CryptoProvider process-wide before any TLS handshake.
    // reqwest builds its own config, but tokio-tungstenite's wss:// path calls
    // ClientConfig::builder(), which resolves the process-default provider and
    // panics if the crate features ever expose more than one (or none). Pin ring
    // explicitly so public wss:// gateways (VPS/VPC with a real cert) work. This
    // is idempotent — ignore the Err when something already installed one.
    let _ = rustls::crypto::ring::default_provider().install_default();

    let builder = tauri::Builder::default();

    // FIRST in the chain, and that is load-bearing: on Windows/Linux a
    // `hermes://` link launches a SECOND process with the URL as its only
    // argument, and this plugin is what kills that process and hands its argv to
    // the running one. Registering it after another plugin would let that
    // plugin's setup run in the losing instance first. Our callback body is
    // deliberately empty — the plugin's own default already calls the deep-link
    // plugin's `handle_cli_arguments`, and desktop's Electron `app.exit(0)`
    // teardown maps to "do nothing but hand over the argv" here, because nothing
    // in the loser owns anything yet.
    #[cfg(not(any(target_os = "android", target_os = "ios")))]
    let builder = builder.plugin(tauri_plugin_single_instance::Builder::new().build());

    // OS-level hotkeys (MJXHRM-55). Desktop only — no mobile OS lets an app claim
    // a system-wide chord, and the crate isn't in the mobile dependency set at
    // all, so this is a compile-time branch rather than a runtime capability
    // check. Which chords get registered is decided by the frontend from the
    // rebindable keybind registry (`lib/keybinds/global-shortcut.ts`); nothing is
    // hardcoded here.
    #[cfg(not(any(target_os = "android", target_os = "ios")))]
    let builder = builder.plugin(tauri_plugin_global_shortcut::Builder::new().build());

    let builder = builder
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_mic::init())
        // The native WebView guest host. Registered on both targets so the
        // builder chain has one shape; the desktop half is a refusal stub
        // nothing calls (desktop uses a child webview instead).
        .plugin(tauri_plugin_browser::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_haptics::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_notification::init())
        // `hermes://` — the OS front door (see deep_link.rs). Registered on both
        // targets: the scheme is claimed by the bundler on desktop and by the
        // Android intent-filter / iOS CFBundleURLTypes on mobile.
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_clipboard_manager::init());

    // Signed self-update (MJXHRM-144). Desktop-only — the plugin has no mobile
    // implementation, and a phone updates through its store anyway. Driven
    // entirely from `updates.rs`, so the webview never calls it and
    // `capabilities/default.json` needs no updater permission. Bound by a
    // cfg'd shadow rather than a helper because the plugin's `TauriPlugin`
    // carries its own config type, so the two branches aren't one type.
    #[cfg(all(desktop, feature = "update-checks"))]
    let builder = builder.plugin(tauri_plugin_updater::Builder::new().build());

    // A page load starting is a reload (or a first load, which holds nothing):
    // the old page's tunnel leases are gone with its JS, so they end here and a
    // slot they alone held lingers one reaper tick for the new page
    // (MJXHRM-592). Desktop only, and reap-only: the epoch moves when the new
    // page calls `tunnel_page_open`, because on Android `onPageStarted` is not
    // ordered with the page's own IPC. Keyed by the webview's own label, so a
    // browser guest navigating inside a window never touches its leases.
    #[cfg(desktop)]
    let builder = builder.on_page_load(|webview, payload| {
        if tunnels::reaps_on_page_load(&payload.event()) {
            use tauri::Manager;

            tunnels::page_started(webview.app_handle(), webview.label());
        }
    });

    let builder = builder
        .manage(TransportState::new())
        .manage(MediaState::default())
        // The live downloads' cancel flags. Managed on BOTH targets so the
        // builder chain is one shape — and unlike the empty mobile stubs beside
        // it this one is real on the phone too: a download is a network fetch
        // plus a local write, and both halves work there.
        .manage(DownloadState::default())
        .manage(ArtifactState::default())
        .manage(LocalBackendState::default())
        .manage(local_install::InstallState::default())
        .manage(PtyState::default())
        // The one system-sleep inhibitor. It releases on drop, so quitting frees
        // the machine even if the webview never turned the preference back off.
        .manage(KeepAwakeState::default())
        .manage(DataUrlReadMaxState::default())
        .manage(FaviconState::default())
        .manage(HostFactsState::default())
        .manage(AppLogState::default())
        .manage(McpOauthState::default())
        .manage(AmbientState::default())
        .manage(ActiveWorkState::default())
        .manage(IntroRevealState::default())
        .manage(QuickEntryState::default())
        .manage(HudState::default());

    #[cfg(desktop)]
    let builder = builder.manage(HudModifierStateHandle::default());

    #[cfg(desktop)]
    let builder = builder.manage(ScreenshotStateHandle::default());

    #[cfg(desktop)]
    let builder = builder.manage(WatchersState::default());

    builder
        // Which glass request each window LABEL already carries, so a tint drag
        // under glass costs zero native calls (appearance/mod.rs).
        .manage(AppearanceState::default())
        // Which windows already have the context-menu bridge installed
        // (MJXHRM-478). Managed on BOTH targets so the builder chain has one
        // shape; the set is empty and harmless where no adapter exists yet.
        .manage(ContextMenuState::default())
        // The in-app browser's guests and its SSH forward leases (MJXHRM-447).
        // Managed on BOTH targets: desktop hosts a child webview, mobile a
        // native view through tauri-plugin-browser, and the reach lease is
        // platform-independent because russh is not cfg-gated.
        .manage(BrowserState::default())
        // The connection registry (MJXHRM-446). Managed on BOTH targets: the
        // document, the credentials and the probe are platform-identical, and
        // only the `local` KIND is desktop-only.
        .manage(ConnectionsState::default())
        .manage(ManagedUpdateGate::default())
        // The deep-link cold-start buffer. Managed on BOTH targets so the builder
        // chain has one shape — and it does real work on mobile, where a cold
        // launch from a tapped link races the WebView every time.
        .manage(DeepLinkState::default())
        .manage(VoiceState::default())
        .manage(UpdateState::default())
        // Live SSH sessions. Unlike desktop's on-disk control socket, nothing
        // here outlives the process, so there is no stale master to evict.
        .manage(SshState::default())
        .manage(tunnels::TunnelState::default())
        // Background mode's two flags — the mirrored preference, and the
        // one-way "the user asked to quit" latch that stops `ExitRequested`
        // from preventing the app's own exit (background.rs).
        .manage(BackgroundState::default())
        // The tray's live menu rows, so their text can be replaced when the
        // webview pushes the translated catalog. Managed on both targets so
        // the builder chain is the same shape; the mobile `TrayState` is an
        // empty struct nothing reads.
        .manage(TrayState::default())
        // The OS-hotkey registry. Rust holds the claims now, not a webview
        // (MJXHRM-437), so this outlives every window — which is the point:
        // background mode makes "no window is visible" the state the chord has
        // to work in. Managed on both targets so the builder chain is the same
        // shape; the mobile `ShortcutState` is an empty struct nothing reads.
        .manage(ShortcutState::default())
        // Inline audio/video streams through here instead of loading as a base64
        // data URL — see media.rs. Registered on the BUILDER, not in `.setup()`:
        // on Linux, wry registers custom schemes into the WebContext when the
        // webview is created, so a later registration would never take.
        .register_asynchronous_uri_scheme_protocol(MEDIA_SCHEME, media::handle)
        // Model-generated HTML gets an ORIGIN of its own rather than running
        // inside the app document — see artifact.rs. Same builder-time
        // registration for the same wry/Linux reason as above.
        .register_asynchronous_uri_scheme_protocol(ARTIFACT_SCHEME, artifact::handle)
        .setup(|app| {
            // Where the sealed credential vault lives, before anything can ask for a
            // credential: every `secrets_*` command and `gateway_bearer` call arrives
            // after `setup` returns, and on macOS a read that beat this would be
            // refused rather than answered from the wrong place. Not fatal — a machine
            // that names no data directory cannot persist credentials, the same "we
            // store nothing, and say so" outcome `store::ensure` already reports.
            {
                use tauri::Manager;

                match app.path().app_data_dir() {
                    Ok(dir) => secrets::store::configure(dir),
                    Err(e) => log::error!(
                        "[secrets] no app data directory, so credentials cannot be stored: {e}"
                    ),
                }
            }

            // WebKitGTK (Linux desktop) auto-denies `getUserMedia` unless the
            // embedder answers the WebView's `permission-request` signal — wry
            // does not, so voice/dictation fails instantly with a permission
            // error and no prompt. Allow microphone (and camera) requests here so
            // the mic works; Linux has no per-app OS mic gate, so there is nothing
            // further to ask. Non-media requests are left to WebKit's default
            // (deny). No-op on macOS/Windows/mobile, where the webview or the mic
            // plugin already handles permission.
            #[cfg(target_os = "linux")]
            {
                use tauri::Manager;

                if let Some(window) = app.get_webview_window("main") {
                    let _ = window.with_webview(|platform_webview| {
                        use webkit2gtk::glib::prelude::*;
                        use webkit2gtk::{
                            PermissionRequestExt, UserMediaPermissionRequest, WebViewExt,
                        };

                        platform_webview
                            .inner()
                            .connect_permission_request(|_webview, request| {
                                if request
                                    .downcast_ref::<UserMediaPermissionRequest>()
                                    .is_some()
                                {
                                    request.allow();
                                    true
                                } else {
                                    false
                                }
                            });
                    });
                }
            }

            // The tray. Desktop only, and deliberately not fatal: a machine
            // with no StatusNotifier host (a bare sway/wlroots session with no
            // waybar and no xembed tray) is a perfectly good machine to run
            // Hermes on — it just cannot run it hidden, so the flag below is
            // what makes `set_background_mode` refuse to arm rather than
            // stranding a live process with no window and no icon.
            #[cfg(desktop)]
            {
                use tauri::Manager;

                let ready = tray::install(app.handle());

                app.state::<BackgroundState>().set_tray_ready(ready);
            }

            // Logged unconditionally at boot, because the symptom it explains
            // shows up long before anyone thinks to look at `secrets_status`:
            // macOS asking for the login-keychain password. An ad-hoc signed
            // bundle has no code identity a keychain ACL can bind to, so "Always
            // Allow" has nothing to stick to. It is one prompt per launch now
            // rather than one per credential — see `secrets::store` — but one is
            // still one more than a signed build shows.
            if secrets::code_identity::current().prompts_for_keychain_access() {
                log::warn!(
                    "[secrets] this build is ad-hoc signed, so macOS cannot bind a keychain ACL \
                     to it and will ask for your password once per launch to unlock the \
                     credential vault. Only a Developer ID signed build stops that."
                );
            }

            deep_link::setup(app.handle());

            #[cfg(desktop)]
            {
                use tauri::Manager;

                let state = app.state::<QuickEntryState>();
                quick_entry::boot(app.handle(), state.inner());

                let hud_mod = app.state::<HudModifierStateHandle>();
                hud_modifier::boot(app.handle(), hud_mod.inner());

                let shot = app.state::<ScreenshotStateHandle>();
                screenshot::boot(app.handle(), shot.inner());
            }
            tunnels::start_reaper(app.handle());

            let _ = app;
            Ok(())
        })
        // Wrapped so the webview's trace context is entered before dispatch:
        // Tauri builds `ipc::request::handler` and `ipc::request::run` inside
        // the generated command wrapper, so both inherit the remote parent and
        // the backend's spans join the frontend's trace instead of forming
        // their own. The wrapper does NOT time anything — see telemetry.rs.
        .invoke_handler(telemetry::traced_invoke_handler(tauri::generate_handler![
            http_request,
            ws_open,
            ws_send,
            ws_close,
            pty_spawn,
            pty_write,
            pty_resize,
            pty_kill,
            repo_scan_git_repos,
            git_worktree_list,
            git_worktree_add,
            git_worktree_remove,
            git_branch_list,
            git_base_branch_list,
            git_branch_switch,
            git_repo_status,
            git_file_diff,
            git_review_list,
            git_review_diff,
            git_review_stage,
            git_review_unstage,
            git_review_revert,
            git_review_rev_parse,
            git_review_commit,
            git_review_commit_context,
            git_review_push,
            git_review_ship_info,
            git_review_pr_list,
            git_review_create_pr,
            chat_onboarding_grow,
            chat_onboarding_solo_boot,
            intro_reveal_open,
            intro_reveal_close,
            intro_reveal_ready,
            intro_reveal_skip,
            quick_entry_settings_get,
            quick_entry_settings_set,
            pet_overlay_open,
            pet_overlay_close,
            pet_overlay_set_bounds,
            pet_overlay_set_ignore_mouse,
            pet_overlay_set_focusable,
            pet_overlay_push_state,
            pet_overlay_control,
            hud_broadcast_changed,
            hud_set_session,
            hud_set_ignore_mouse,
            hud_set_bounds,
            hud_begin_move,
            hud_end_move,
            hud_move_by,
            hud_set_workspace_transfer,
            hud_reset_layout,
            hud_windowing,
            hud_emit_goto,
            #[cfg(desktop)]
            hud_modifier_settings_get,
            #[cfg(desktop)]
            hud_modifier_settings_set,
            #[cfg(desktop)]
            hud_modifier_open_permission,
            #[cfg(desktop)]
            screenshot_settings_get,
            #[cfg(desktop)]
            screenshot_settings_set,
            #[cfg(desktop)]
            screenshot_open_permission,
            #[cfg(desktop)]
            screenshot_subscribe,
            #[cfg(desktop)]
            screenshot_capture,
            voice_open,
            voice_arm,
            voice_wake_listen,
            voice_suspend,
            voice_force_turn,
            voice_update_auth,
            voice_close,
            open_external,
            reveal_in_file_manager,
            #[cfg(desktop)]
            open_in_terminal,
            #[cfg(desktop)]
            open_session_in_terminal,
            #[cfg(desktop)]
            fs_read_dir,
            #[cfg(desktop)]
            fs_git_root,
            #[cfg(desktop)]
            fs_open_dir,
            #[cfg(desktop)]
            fs_rename,
            #[cfg(desktop)]
            fs_write_text,
            #[cfg(desktop)]
            fs_trash,
            #[cfg(desktop)]
            sanitize_workspace_cwd,
            #[cfg(desktop)]
            read_file_text,
            #[cfg(desktop)]
            normalize_preview_target,
            #[cfg(desktop)]
            watch_preview_file,
            #[cfg(desktop)]
            watch_directory,
            #[cfg(desktop)]
            stop_preview_file_watch,
            appearance_capabilities,
            appearance_set_glass,
            set_keep_awake,
            set_data_url_read_max,
            read_capped_file_base64,
            read_capped_file_base64_for_attach,
            save_image_buffer,
            save_pasted_text,
            save_clipboard_image,
            resolve_favicon,
            get_on_battery,
            get_machine_profile,
            get_remote_display_reason,
            logs_root,
            logs_reveal,
            logs_recent,
            report_renderer_error,
            mcp_oauth_listen,
            mcp_oauth_wait,
            mcp_oauth_cancel,
            profile_default_get,
            profile_default_set,
            claim_ambient_cue,
            set_active_work,
            #[cfg(desktop)]
            capture_preview,
            get_app_flag,
            set_app_flag,
            connections_list,
            connections_migrate,
            connections_save,
            connections_remove,
            connections_set_primary,
            connections_set_launch_mode,
            connections_set_last_used,
            connections_current_source,
            connections_commit_source,
            connections_claim_resume,
            connections_resolve,
            connections_test,
            connections_roster,
            connections_update_all,
            connections_update_managed,
            marketplace_search,
            marketplace_fetch,
            artifact_release,
            artifact_stage,
            media_set_target,
            download_file,
            download_folder,
            cancel_download,
            fetch_link_title,
            oauth_login,
            oauth_status,
            oauth_logout,
            cookies_clear,
            cookies_export,
            cookies_import,
            local_backend_spawn,
            local_backend_status,
            local_backend_stop,
            local_backend_restart,
            local_backend_kill,
            tunnels::tunnel_acquire,
            tunnels::tunnel_release,
            tunnels::tunnel_page_open,
            tunnels::tunnel_status,
            local_install_detect,
            local_install_start,
            local_install_cancel,
            portal_login,
            portal_status,
            portal_discover_agents,
            portal_agent_sign_in,
            portal_logout,
            plugins_root,
            plugins_list,
            plugins_read,
            plugins_probe,
            plugins_install_desktop,
            plugins_remove_desktop,
            open_session_window,
            open_instance_window,
            open_tile_window,
            open_browser_window,
            open_screen_window,
            open_satellite_window,
            hide_satellite_window,
            is_satellite_window_visible,
            resize_satellite_window,
            update_check,
            update_install,
            update_open_download,
            relaunch_app,
            ssh_connect,
            ssh_test,
            ssh_disconnect,
            ssh_cancel,
            ssh_list_config_hosts,
            ssh_resolve_host,
            ssh_answer_prompt,
            ssh_trust_host_key,
            ssh_install,
            secrets_get,
            secrets_set,
            secrets_delete,
            secrets_clear,
            secrets_status,
            secrets_unlock,
            secrets_lock,
            find_in_page,
            stop_find_in_page,
            context_menu_install,
            context_menu_set_suppressed,
            context_menu_copy_image,
            context_menu_save_image,
            surface_capabilities,
            surface_set_interactive_rect,
            read_window_below,
            set_background_mode,
            get_background_mode,
            quit_app,
            show_app_window,
            hide_this_window,
            close_this_window,
            tray_set_labels,
            tray_set_status,
            global_shortcuts_sync,
            global_shortcut_take_pending,
            deep_link_ready,
            browser_capabilities,
            browser_open,
            browser_navigate,
            browser_back,
            browser_forward,
            browser_reload,
            browser_stop,
            browser_set_bounds,
            browser_set_visible,
            browser_eval,
            browser_clear_data,
            browser_open_devtools,
            browser_close,
            browser_reach_url,
            browser_reach_reset
        ]))
        // `.build(...).run(closure)` (rather than the terminal `.run(context)`) so
        // we can observe `RunEvent`s. On iOS this catches scenes the *system*
        // requests unprompted (state restoration, iPad app-switcher "+", Handoff)
        // and fills them with a fresh instance (MJX-142); app-initiated session
        // windows go through `open_session_window` and never emit this event.
        // Non-iOS targets run the loop with an empty handler — behaviour unchanged.
        .build(tauri::generate_context!())
        .expect("error while building Hermes Universal")
        .run(|app_handle, event| {
            let _ = app_handle;

            // Drop the credential unlock the moment the app stops being in front
            // of the user. A short lease is only worth having if walking away
            // ends it, and "no window has focus" / "the app is suspending" is the
            // closest signal we get to that. Losing it costs one extra prompt;
            // keeping it costs an unattended machine with the credentials open.
            //
            // A sign-in is the one defocus that is not the user walking away — see
            // `defocus_ends_the_lease`.
            match &event {
                tauri::RunEvent::WindowEvent {
                    label,
                    event: tauri::WindowEvent::Focused(false),
                    ..
                } if defocus_ends_the_lease(label) => secrets::gate::lock(),

                // Suspending or quitting always ends it, sign-in or not.
                tauri::RunEvent::ExitRequested { .. } => secrets::gate::lock(),

                _ => {}
            }

            #[cfg(target_os = "ios")]
            if let tauri::RunEvent::SceneRequested { .. } = &event {
                window::fill_requested_scene(app_handle);
            }

            // A second window went away. Both arms live here rather than in the
            // closing webview because a torn-down WebKitGTK view is the least
            // reliable place to send a message from; tao reports the destroy
            // whether or not the page got a chance to run anything.
            //
            //  • a detached tile: so the tile goes back in its slot (MJXHRM-173)
            //  • a satellite: so the main window can reclaim the gateway stream
            //    the HUD was holding (MJXHRM-371)
            //  • a Browser pop-out: so the primary window can dock the tab again
            //  • ANY window: so the shells it spawned die with it (MJXHRM-373).
            //    `pty_kill` is only ever called by the terminal component's
            //    unmount cleanup, and that never runs for a natively closed
            //    window — so a detached terminal tile left one orphaned shell
            //    per close, running for the rest of the app's life.
            //  • ANY window: and so do the WebSockets it opened (MJXHRM-405).
            //    `ws_close` has exactly the same problem — it only ever runs
            //    from a JS disposer — while the socket itself lives in Rust and
            //    outlives the WebView, still reading frames and emitting events
            //    at a window that is gone.
            if let tauri::RunEvent::WindowEvent {
                label,
                event: tauri::WindowEvent::Destroyed,
                ..
            } = &event
            {
                use tauri::{Emitter, Manager};

                #[cfg(desktop)]
                pty::reap_window_ptys(app_handle, label);

                transport::reap_window_sockets(app_handle, label);
                // …and so do the tunnel leases it held (MJXHRM-592).
                tunnels::window_destroyed(app_handle, label);
                appearance::reap_window(app_handle, label);
                // …and so do the guest webviews it hosted (MJXHRM-447): a child
                // webview dies with its window, but the Rust-side registry
                // would keep answering for it.
                browser::reap_window(app_handle, label);

                if let Some(state) = app_handle.try_state::<ActiveWorkState>() {
                    state.forget(label);
                }

                // The main webview is gone (a reload, an Android process
                // recreation). Stop claiming a listener exists, so the next link
                // buffers until its replacement calls `deep_link_ready` again —
                // without this, an F5 during development silently swallows every
                // later link.
                if label == "main" {
                    deep_link::forget_ready(app_handle);
                }

                if window::is_tile_window_label(label) {
                    let _ = app_handle.emit(window::TILE_WINDOW_CLOSED_EVENT, label.clone());
                }
                if window::is_satellite_window_label(label) {
                    let _ = app_handle.emit(window::SATELLITE_WINDOW_CLOSED_EVENT, label.clone());
                }
                if window::is_browser_window_label(label) {
                    if let Some(tab_id) = window::take_browser_tab_id(label) {
                        let _ = app_handle.emit(window::BROWSER_WINDOW_CLOSED_EVENT, tab_id);
                    }
                }
                if label == intro_reveal::WINDOW_LABEL {
                    if let Some(state) = app_handle.try_state::<IntroRevealState>() {
                        intro_reveal::on_destroyed(app_handle, &state);
                    }
                }
            }

            // Background mode's hold on the process (MJXHRM-436).
            //
            // tao raises `ExitRequested` the moment the window map empties —
            // `tauri-runtime-wry` fires it from `TaoWindowEvent::Destroyed` and
            // then sets `ControlFlow::Exit` unless something prevents it — so
            // without this arm destroying the last window ends the process, and
            // "keep running in the background" would end at the first close that
            // was not a hide.
            //
            // It is NOT the hide mechanism. Close-to-hide is decided in JS, in
            // `installWindowCloseGuard`, because Tauri's core calls
            // `prevent_close()` for any window that has a JS
            // `tauri://close-requested` listener — so a Rust `CloseRequested` arm
            // would be fighting a handler that has already won. This arm is the
            // guard for every other route to zero windows: the macOS
            // last-window-closed quit, a window destroyed natively by the
            // compositor, a satellite teardown that took the last one with it.
            //
            // The `quit_requested` half is what keeps Tray → Quit working:
            // `AppHandle::exit` raises this same event.
            #[cfg(desktop)]
            if let tauri::RunEvent::ExitRequested { api, .. } = &event {
                use tauri::Manager;

                if app_handle.state::<BackgroundState>().should_prevent_exit() {
                    api.prevent_exit();
                } else if active_work::hold_exit_for_active_work(app_handle) {
                    api.prevent_exit();
                }
            }

            // Flush pending spans before the process goes away. The batch
            // exporter holds them in memory, and the last batch is usually the
            // interesting one — whatever happened right before the user quit.
            // No-op without the tracing feature.
            if let tauri::RunEvent::Exit = &event {
                // Every tunnel goes, and the local child with it, whoever holds
                // them (MJXHRM-592).
                tunnels::shutdown(app_handle);
                telemetry::shutdown();
            }

            let _ = event;
        });
}
