//! Hermes Universal — Tauri v2 entrypoint (shared by desktop dev and the mobile
//! Android/iOS targets). `run()` is the mobile entry point; the Android project
//! generated by `tauri android init` calls into it.
//!
//! All network traffic runs in Rust (`transport`), not the webview — see
//! `transport.rs`. The frontend drives it over IPC and reuses the JS
//! `JsonRpcGatewayClient` via an IPC-backed WebSocket.
//!
//! (Android note: the generated `RustWebView.getCookies` is patched null-safe by
//! `build.rs` to avoid a wry 0.55 crash on cookie polling — see that file.)

mod app_state;
mod appearance;
mod artifact;
mod background;
mod cloud;
mod data_url_read_max;
#[cfg(desktop)]
mod external_terminal;
mod find_in_page;
mod keep_awake;
mod link_title;
mod local_backend;
mod local_install;
mod marketplace;
mod media;
mod oauth;
mod plugins;
mod pty;
mod repo_scan;
mod secrets;
mod shortcuts;
mod ssh;
mod surface;
mod telemetry;
mod transport;
mod tray;
mod updates;
mod voice;
mod webview_cookies;
mod window;

use app_state::{get_app_flag, set_app_flag};
use appearance::set_window_translucency;
use artifact::{artifact_release, artifact_stage, ArtifactState, ARTIFACT_SCHEME};
use background::{get_background_mode, quit_app, set_background_mode, BackgroundState};
use cloud::{
    portal_agent_sign_in, portal_discover_agents, portal_login, portal_logout, portal_status,
};
use data_url_read_max::{read_capped_file_base64, set_data_url_read_max, DataUrlReadMaxState};
#[cfg(desktop)]
use external_terminal::open_in_terminal;
use find_in_page::{find_in_page, stop_find_in_page};
use keep_awake::{set_keep_awake, KeepAwakeState};
use link_title::fetch_link_title;
use local_backend::{
    local_backend_spawn, local_backend_status, local_backend_stop, LocalBackendState,
};
use local_install::{local_install_cancel, local_install_detect, local_install_start};
use marketplace::{marketplace_fetch, marketplace_search};
use media::{media_set_target, MediaState, MEDIA_SCHEME};
use oauth::{oauth_login, oauth_logout, oauth_status};
use plugins::{plugins_list, plugins_read, plugins_root};
use pty::{pty_kill, pty_resize, pty_spawn, pty_write, PtyState};
use repo_scan::repo_scan_git_repos;
use secrets::{
    secrets_clear, secrets_delete, secrets_get, secrets_lock, secrets_set, secrets_status,
    secrets_unlock,
};
use shortcuts::{global_shortcut_take_pending, global_shortcuts_sync, ShortcutState};
use ssh::{
    ssh_answer_prompt, ssh_cancel, ssh_connect, ssh_disconnect, ssh_install, ssh_list_config_hosts,
    ssh_resolve_host, ssh_test, ssh_trust_host_key, SshState,
};
use surface::below::read_window_below;
use surface::{surface_capabilities, surface_set_interactive_rect};
use transport::{
    cookies_export, cookies_import, http_request, ws_close, ws_open, ws_send, TransportState,
};
use tray::{tray_set_labels, tray_set_status, TrayState};
use updates::{update_check, update_open_download, UpdateState};
use voice::{
    voice_arm, voice_close, voice_force_turn, voice_open, voice_suspend, voice_update_auth,
    voice_wake_listen, VoiceState,
};
use window::{
    close_this_window, hide_satellite_window, hide_this_window, is_satellite_window_visible,
    open_instance_window, open_satellite_window, open_screen_window, open_session_window,
    open_tile_window, resize_satellite_window, show_app_window,
};

/// Open a URL in the system browser. Routed through the opener plugin's Rust API
/// rather than its JS `openUrl` command: a Rust-internal call isn't gated by the
/// opener ACL/scope (which was silently blocking the JS path), so provider OAuth
/// sign-in and docs links reliably launch the OS browser.
#[tauri::command]
fn open_external(app: tauri::AppHandle, url: String) -> Result<(), String> {
    use tauri_plugin_opener::OpenerExt;
    app.opener()
        .open_url(url, None::<&str>)
        .map_err(|e| e.to_string())
}

/// Reveal a path in the OS file manager (Finder/Explorer/Files), selecting the
/// item. Routed through the opener plugin's Rust API — like `open_external`, a
/// Rust-internal call isn't gated by the opener ACL/scope. Desktop-local only:
/// the caller must ensure the path exists on this machine's disk.
#[tauri::command]
fn reveal_in_file_manager(app: tauri::AppHandle, path: String) -> Result<(), String> {
    use tauri_plugin_opener::OpenerExt;
    app.opener()
        .reveal_item_in_dir(path)
        .map_err(|e| e.to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Route Rust `log::` output somewhere a person can read it on mobile (tao
    // doesn't reliably install a logger, so diagnostics were invisible).
    #[cfg(target_os = "android")]
    android_logger::init_once(
        android_logger::Config::default()
            .with_max_level(log::LevelFilter::Info)
            .with_tag("hermes"),
    );

    // The iOS half, added because its absence hid a real bug for a whole debugging
    // session: an ATS-blocked sign-in navigation is reported ONLY as a `log::error!`
    // from inside wry's event loop, and with no logger installed that line — and
    // every `[oauth]`/`[portal]` breadcrumb next to it — went nowhere. The symptom
    // was "the button does nothing", with no way to tell a refused navigation from a
    // command that never ran.
    //
    // Deliberately fire-and-forget, exactly like `init_once` above: `telemetry::init`
    // below may install `tracing_log::LogTracer` as the global logger first, and
    // losing that race must cost us a log sink, never the app. (This is also why the
    // richer `tauri-plugin-log` is not used here — it installs its logger from plugin
    // setup and turns the same race into a failed build.)
    // The subsystem is the iOS bundle identifier (tauri.conf.json `identifier`), so
    // `log stream --predicate 'subsystem == "com.jaxmatrix.mjx-unofficial-hermes"'`
    // filters to just this app. Note the hyphens — the Android namespace above spells
    // the same id with underscores, and only this form matches the iOS bundle.
    #[cfg(target_os = "ios")]
    let _ = oslog::OsLogger::new("com.jaxmatrix.mjx-unofficial-hermes")
        .level_filter(log::LevelFilter::Info)
        .init();

    // Span tracing. FIRST, so boot itself lands inside the trace rather than
    // before it. Compiled out entirely without `--features tracing`, and inert
    // even then unless HERMES_TRACE=1 — see telemetry.rs for why it is two
    // switches rather than one.
    telemetry::init();

    // Install a rustls CryptoProvider process-wide before any TLS handshake.
    // reqwest builds its own config, but tokio-tungstenite's wss:// path calls
    // ClientConfig::builder(), which resolves the process-default provider and
    // panics if the crate features ever expose more than one (or none). Pin ring
    // explicitly so public wss:// gateways (VPS/VPC with a real cert) work. This
    // is idempotent — ignore the Err when something already installed one.
    let _ = rustls::crypto::ring::default_provider().install_default();

    let builder = tauri::Builder::default();

    // OS-level hotkeys (MJXHRM-55). Desktop only — no mobile OS lets an app claim
    // a system-wide chord, and the crate isn't in the mobile dependency set at
    // all, so this is a compile-time branch rather than a runtime capability
    // check. Which chords get registered is decided by the frontend from the
    // rebindable keybind registry (`lib/keybinds/global-shortcut.ts`); nothing is
    // hardcoded here.
    #[cfg(not(any(target_os = "android", target_os = "ios")))]
    let builder = builder.plugin(tauri_plugin_global_shortcut::Builder::new().build());

    builder
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_mic::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_haptics::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_clipboard_manager::init())
        .manage(TransportState::new())
        .manage(MediaState::default())
        .manage(ArtifactState::default())
        .manage(LocalBackendState::default())
        .manage(local_install::InstallState::default())
        .manage(PtyState::default())
        // The one system-sleep inhibitor. It releases on drop, so quitting frees
        // the machine even if the webview never turned the preference back off.
        .manage(KeepAwakeState::default())
        .manage(DataUrlReadMaxState::default())
        .manage(VoiceState::default())
        .manage(UpdateState::default())
        // Live SSH sessions. Unlike desktop's on-disk control socket, nothing
        // here outlives the process, so there is no stale master to evict.
        .manage(SshState::default())
        // Background mode's two flags — the mirrored preference, and the
        // one-way "the user asked to quit" latch that stops `ExitRequested`
        // from preventing the app's own exit (background.rs).
        .manage(BackgroundState::default())
        // The tray's live menu rows, so their text can be replaced when the
        // webview pushes the translated catalog. Managed on both targets so
        // the builder chain is the same shape; the mobile `TrayState` is an
        // empty struct nothing reads.
        .manage(TrayState::default())
        // The OS-hotkey registry. Rust holds the claims now, not a webview
        // (MJXHRM-437), so this outlives every window — which is the point:
        // background mode makes "no window is visible" the state the chord has
        // to work in. Managed on both targets so the builder chain is the same
        // shape; the mobile `ShortcutState` is an empty struct nothing reads.
        .manage(ShortcutState::default())
        // Inline audio/video streams through here instead of loading as a base64
        // data URL — see media.rs. Registered on the BUILDER, not in `.setup()`:
        // on Linux, wry registers custom schemes into the WebContext when the
        // webview is created, so a later registration would never take.
        .register_asynchronous_uri_scheme_protocol(MEDIA_SCHEME, media::handle)
        // Model-generated HTML gets an ORIGIN of its own rather than running
        // inside the app document — see artifact.rs. Same builder-time
        // registration for the same wry/Linux reason as above.
        .register_asynchronous_uri_scheme_protocol(ARTIFACT_SCHEME, artifact::handle)
        .setup(|app| {
            // WebKitGTK (Linux desktop) auto-denies `getUserMedia` unless the
            // embedder answers the WebView's `permission-request` signal — wry
            // does not, so voice/dictation fails instantly with a permission
            // error and no prompt. Allow microphone (and camera) requests here so
            // the mic works; Linux has no per-app OS mic gate, so there is nothing
            // further to ask. Non-media requests are left to WebKit's default
            // (deny). No-op on macOS/Windows/mobile, where the webview or the mic
            // plugin already handles permission.
            #[cfg(target_os = "linux")]
            {
                use tauri::Manager;

                if let Some(window) = app.get_webview_window("main") {
                    let _ = window.with_webview(|platform_webview| {
                        use webkit2gtk::glib::prelude::*;
                        use webkit2gtk::{
                            PermissionRequestExt, UserMediaPermissionRequest, WebViewExt,
                        };

                        platform_webview
                            .inner()
                            .connect_permission_request(|_webview, request| {
                                if request
                                    .downcast_ref::<UserMediaPermissionRequest>()
                                    .is_some()
                                {
                                    request.allow();
                                    true
                                } else {
                                    false
                                }
                            });
                    });
                }
            }

            // The tray. Desktop only, and deliberately not fatal: a machine
            // with no StatusNotifier host (a bare sway/wlroots session with no
            // waybar and no xembed tray) is a perfectly good machine to run
            // Hermes on — it just cannot run it hidden, so the flag below is
            // what makes `set_background_mode` refuse to arm rather than
            // stranding a live process with no window and no icon.
            #[cfg(desktop)]
            {
                use tauri::Manager;

                let ready = tray::install(app.handle());

                app.state::<BackgroundState>().set_tray_ready(ready);
            }

            let _ = app;
            Ok(())
        })
        // Wrapped so the webview's trace context is entered before dispatch:
        // Tauri builds `ipc::request::handler` and `ipc::request::run` inside
        // the generated command wrapper, so both inherit the remote parent and
        // the backend's spans join the frontend's trace instead of forming
        // their own. The wrapper does NOT time anything — see telemetry.rs.
        .invoke_handler(telemetry::traced_invoke_handler(tauri::generate_handler![
            http_request,
            ws_open,
            ws_send,
            ws_close,
            pty_spawn,
            pty_write,
            pty_resize,
            pty_kill,
            repo_scan_git_repos,
            voice_open,
            voice_arm,
            voice_wake_listen,
            voice_suspend,
            voice_force_turn,
            voice_update_auth,
            voice_close,
            open_external,
            reveal_in_file_manager,
            #[cfg(desktop)]
            open_in_terminal,
            set_window_translucency,
            set_keep_awake,
            set_data_url_read_max,
            read_capped_file_base64,
            get_app_flag,
            set_app_flag,
            marketplace_search,
            marketplace_fetch,
            artifact_release,
            artifact_stage,
            media_set_target,
            fetch_link_title,
            oauth_login,
            oauth_status,
            oauth_logout,
            cookies_export,
            cookies_import,
            local_backend_spawn,
            local_backend_status,
            local_backend_stop,
            local_install_detect,
            local_install_start,
            local_install_cancel,
            portal_login,
            portal_status,
            portal_discover_agents,
            portal_agent_sign_in,
            portal_logout,
            plugins_root,
            plugins_list,
            plugins_read,
            open_session_window,
            open_instance_window,
            open_tile_window,
            open_screen_window,
            open_satellite_window,
            hide_satellite_window,
            is_satellite_window_visible,
            resize_satellite_window,
            update_check,
            update_open_download,
            ssh_connect,
            ssh_test,
            ssh_disconnect,
            ssh_cancel,
            ssh_list_config_hosts,
            ssh_resolve_host,
            ssh_answer_prompt,
            ssh_trust_host_key,
            ssh_install,
            secrets_get,
            secrets_set,
            secrets_delete,
            secrets_clear,
            secrets_status,
            secrets_unlock,
            secrets_lock,
            find_in_page,
            stop_find_in_page,
            surface_capabilities,
            surface_set_interactive_rect,
            read_window_below,
            set_background_mode,
            get_background_mode,
            quit_app,
            show_app_window,
            hide_this_window,
            close_this_window,
            tray_set_labels,
            tray_set_status,
            global_shortcuts_sync,
            global_shortcut_take_pending
        ]))
        // `.build(...).run(closure)` (rather than the terminal `.run(context)`) so
        // we can observe `RunEvent`s. On iOS this catches scenes the *system*
        // requests unprompted (state restoration, iPad app-switcher "+", Handoff)
        // and fills them with a fresh instance (MJX-142); app-initiated session
        // windows go through `open_session_window` and never emit this event.
        // Non-iOS targets run the loop with an empty handler — behaviour unchanged.
        .build(tauri::generate_context!())
        .expect("error while building Hermes Universal")
        .run(|app_handle, event| {
            let _ = app_handle;

            // Drop the credential unlock the moment the app stops being in front
            // of the user. A short lease is only worth having if walking away
            // ends it, and "no window has focus" / "the app is suspending" is the
            // closest signal we get to that. Losing it costs one extra prompt;
            // keeping it costs an unattended machine with the credentials open.
            match &event {
                tauri::RunEvent::WindowEvent {
                    event: tauri::WindowEvent::Focused(false),
                    ..
                }
                | tauri::RunEvent::ExitRequested { .. } => secrets::gate::lock(),

                _ => {}
            }

            #[cfg(target_os = "ios")]
            if let tauri::RunEvent::SceneRequested { .. } = &event {
                window::fill_requested_scene(app_handle);
            }

            // A second window went away. Both arms live here rather than in the
            // closing webview because a torn-down WebKitGTK view is the least
            // reliable place to send a message from; tao reports the destroy
            // whether or not the page got a chance to run anything.
            //
            //  • a detached tile: so the tile goes back in its slot (MJXHRM-173)
            //  • a satellite: so the main window can reclaim the gateway stream
            //    the HUD was holding (MJXHRM-371)
            //  • ANY window: so the shells it spawned die with it (MJXHRM-373).
            //    `pty_kill` is only ever called by the terminal component's
            //    unmount cleanup, and that never runs for a natively closed
            //    window — so a detached terminal tile left one orphaned shell
            //    per close, running for the rest of the app's life.
            //  • ANY window: and so do the WebSockets it opened (MJXHRM-405).
            //    `ws_close` has exactly the same problem — it only ever runs
            //    from a JS disposer — while the socket itself lives in Rust and
            //    outlives the WebView, still reading frames and emitting events
            //    at a window that is gone.
            if let tauri::RunEvent::WindowEvent {
                label,
                event: tauri::WindowEvent::Destroyed,
                ..
            } = &event
            {
                use tauri::Emitter;

                #[cfg(desktop)]
                pty::reap_window_ptys(app_handle, label);

                transport::reap_window_sockets(app_handle, label);

                if window::is_tile_window_label(label) {
                    let _ = app_handle.emit(window::TILE_WINDOW_CLOSED_EVENT, label.clone());
                }
                if window::is_satellite_window_label(label) {
                    let _ = app_handle.emit(window::SATELLITE_WINDOW_CLOSED_EVENT, label.clone());
                }
            }

            // Background mode's hold on the process (MJXHRM-436).
            //
            // tao raises `ExitRequested` the moment the window map empties —
            // `tauri-runtime-wry` fires it from `TaoWindowEvent::Destroyed` and
            // then sets `ControlFlow::Exit` unless something prevents it — so
            // without this arm destroying the last window ends the process, and
            // "keep running in the background" would end at the first close that
            // was not a hide.
            //
            // It is NOT the hide mechanism. Close-to-hide is decided in JS, in
            // `installWindowCloseGuard`, because Tauri's core calls
            // `prevent_close()` for any window that has a JS
            // `tauri://close-requested` listener — so a Rust `CloseRequested` arm
            // would be fighting a handler that has already won. This arm is the
            // guard for every other route to zero windows: the macOS
            // last-window-closed quit, a window destroyed natively by the
            // compositor, a satellite teardown that took the last one with it.
            //
            // The `quit_requested` half is what keeps Tray → Quit working:
            // `AppHandle::exit` raises this same event.
            #[cfg(desktop)]
            if let tauri::RunEvent::ExitRequested { api, .. } = &event {
                use tauri::Manager;

                if app_handle.state::<BackgroundState>().should_prevent_exit() {
                    api.prevent_exit();
                }
            }

            // Flush pending spans before the process goes away. The batch
            // exporter holds them in memory, and the last batch is usually the
            // interesting one — whatever happened right before the user quit.
            // No-op without the tracing feature.
            if let tauri::RunEvent::Exit = &event {
                telemetry::shutdown();
            }

            let _ = event;
        });
}
