//! Hermes Universal — Tauri v2 entrypoint (shared by desktop dev and the mobile
//! Android/iOS targets). `run()` is the mobile entry point; the Android project
//! generated by `tauri android init` calls into it.
//!
//! All network traffic runs in Rust (`transport`), not the webview — see
//! `transport.rs`. The frontend drives it over IPC and reuses the JS
//! `JsonRpcGatewayClient` via an IPC-backed WebSocket.
//!
//! (Android note: the generated `RustWebView.getCookies` is patched null-safe by
//! `build.rs` to avoid a wry 0.55 crash on cookie polling — see that file.)

mod appearance;
mod cloud;
mod link_title;
mod local_backend;
mod marketplace;
mod oauth;
mod plugins;
mod pty;
mod repo_scan;
mod ssh;
mod telemetry;
mod transport;
mod updates;
mod voice;
mod window;

use appearance::set_window_translucency;
use link_title::fetch_link_title;
use marketplace::{marketplace_fetch, marketplace_search};
use cloud::{
    portal_agent_sign_in, portal_discover_agents, portal_login, portal_logout, portal_status,
};
use local_backend::{local_backend_spawn, local_backend_status, local_backend_stop, LocalBackendState};
use oauth::{oauth_login, oauth_logout, oauth_status};
use plugins::{plugins_list, plugins_read, plugins_root};
use pty::{pty_kill, pty_resize, pty_spawn, pty_write, PtyState};
use repo_scan::repo_scan_git_repos;
use ssh::{
    ssh_answer_prompt, ssh_cancel, ssh_connect, ssh_disconnect, ssh_list_config_hosts,
    ssh_resolve_host, ssh_test, ssh_trust_host_key, SshState,
};
use transport::{
    cookies_export, cookies_import, http_request, ws_close, ws_open, ws_send, TransportState,
};
use updates::{update_check, update_open_download, UpdateState};
use voice::{
    voice_arm, voice_close, voice_force_turn, voice_open, voice_suspend, voice_update_auth,
    VoiceState,
};
use window::{open_instance_window, open_screen_window, open_session_window, open_tile_window};

/// Open a URL in the system browser. Routed through the opener plugin's Rust API
/// rather than its JS `openUrl` command: a Rust-internal call isn't gated by the
/// opener ACL/scope (which was silently blocking the JS path), so provider OAuth
/// sign-in and docs links reliably launch the OS browser.
#[tauri::command]
fn open_external(app: tauri::AppHandle, url: String) -> Result<(), String> {
    use tauri_plugin_opener::OpenerExt;
    app.opener()
        .open_url(url, None::<&str>)
        .map_err(|e| e.to_string())
}

/// Reveal a path in the OS file manager (Finder/Explorer/Files), selecting the
/// item. Routed through the opener plugin's Rust API — like `open_external`, a
/// Rust-internal call isn't gated by the opener ACL/scope. Desktop-local only:
/// the caller must ensure the path exists on this machine's disk.
#[tauri::command]
fn reveal_in_file_manager(app: tauri::AppHandle, path: String) -> Result<(), String> {
    use tauri_plugin_opener::OpenerExt;
    app.opener()
        .reveal_item_in_dir(path)
        .map_err(|e| e.to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Route Rust `log::` output to logcat on Android (tao doesn't reliably install
    // a logger, so diagnostics were invisible). Idempotent via `init_once`.
    #[cfg(target_os = "android")]
    android_logger::init_once(
        android_logger::Config::default()
            .with_max_level(log::LevelFilter::Info)
            .with_tag("hermes"),
    );

    // Span tracing. FIRST, so boot itself lands inside the trace rather than
    // before it. Compiled out entirely without `--features tracing`, and inert
    // even then unless HERMES_TRACE=1 — see telemetry.rs for why it is two
    // switches rather than one.
    telemetry::init();

    // Install a rustls CryptoProvider process-wide before any TLS handshake.
    // reqwest builds its own config, but tokio-tungstenite's wss:// path calls
    // ClientConfig::builder(), which resolves the process-default provider and
    // panics if the crate features ever expose more than one (or none). Pin ring
    // explicitly so public wss:// gateways (VPS/VPC with a real cert) work. This
    // is idempotent — ignore the Err when something already installed one.
    let _ = rustls::crypto::ring::default_provider().install_default();

    tauri::Builder::default()
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_keyring::init())
        .plugin(tauri_plugin_mic::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_haptics::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_notification::init())
        .manage(TransportState::new())
        .manage(LocalBackendState::default())
        .manage(PtyState::default())
        .manage(VoiceState::default())
        .manage(UpdateState::default())
        // Live SSH sessions. Unlike desktop's on-disk control socket, nothing
        // here outlives the process, so there is no stale master to evict.
        .manage(SshState::default())
        .setup(|app| {
            // WebKitGTK (Linux desktop) auto-denies `getUserMedia` unless the
            // embedder answers the WebView's `permission-request` signal — wry
            // does not, so voice/dictation fails instantly with a permission
            // error and no prompt. Allow microphone (and camera) requests here so
            // the mic works; Linux has no per-app OS mic gate, so there is nothing
            // further to ask. Non-media requests are left to WebKit's default
            // (deny). No-op on macOS/Windows/mobile, where the webview or the mic
            // plugin already handles permission.
            #[cfg(target_os = "linux")]
            {
                use tauri::Manager;

                if let Some(window) = app.get_webview_window("main") {
                    let _ = window.with_webview(|platform_webview| {
                        use webkit2gtk::glib::prelude::*;
                        use webkit2gtk::{
                            PermissionRequestExt, UserMediaPermissionRequest, WebViewExt,
                        };

                        platform_webview
                            .inner()
                            .connect_permission_request(|_webview, request| {
                                if request
                                    .downcast_ref::<UserMediaPermissionRequest>()
                                    .is_some()
                                {
                                    request.allow();
                                    true
                                } else {
                                    false
                                }
                            });
                    });
                }
            }

            let _ = app;
            Ok(())
        })
        // Wrapped so the webview's trace context is entered before dispatch:
        // Tauri builds `ipc::request::handler` and `ipc::request::run` inside
        // the generated command wrapper, so both inherit the remote parent and
        // the backend's spans join the frontend's trace instead of forming
        // their own. The wrapper does NOT time anything — see telemetry.rs.
        .invoke_handler(telemetry::traced_invoke_handler(tauri::generate_handler![
            http_request,
            ws_open,
            ws_send,
            ws_close,
            pty_spawn,
            pty_write,
            pty_resize,
            pty_kill,
            repo_scan_git_repos,
            voice_open,
            voice_arm,
            voice_suspend,
            voice_force_turn,
            voice_update_auth,
            voice_close,
            open_external,
            reveal_in_file_manager,
            set_window_translucency,
            marketplace_search,
            marketplace_fetch,
            fetch_link_title,
            oauth_login,
            oauth_status,
            oauth_logout,
            cookies_export,
            cookies_import,
            local_backend_spawn,
            local_backend_status,
            local_backend_stop,
            portal_login,
            portal_status,
            portal_discover_agents,
            portal_agent_sign_in,
            portal_logout,
            plugins_root,
            plugins_list,
            plugins_read,
            open_session_window,
            open_instance_window,
            open_tile_window,
            open_screen_window,
            update_check,
            update_open_download,
            ssh_connect,
            ssh_test,
            ssh_disconnect,
            ssh_cancel,
            ssh_list_config_hosts,
            ssh_resolve_host,
            ssh_answer_prompt,
            ssh_trust_host_key
        ]))
        // `.build(...).run(closure)` (rather than the terminal `.run(context)`) so
        // we can observe `RunEvent`s. On iOS this catches scenes the *system*
        // requests unprompted (state restoration, iPad app-switcher "+", Handoff)
        // and fills them with a fresh instance (MJX-142); app-initiated session
        // windows go through `open_session_window` and never emit this event.
        // Non-iOS targets run the loop with an empty handler — behaviour unchanged.
        .build(tauri::generate_context!())
        .expect("error while building Hermes Universal")
        .run(|app_handle, event| {
            let _ = app_handle;
            #[cfg(target_os = "ios")]
            if let tauri::RunEvent::SceneRequested { .. } = &event {
                window::fill_requested_scene(app_handle);
            }

            // A detached tile's window went away — tell the app so the tile goes
            // back in its slot (MJXHRM-173). This lives here rather than in the
            // closing webview because a torn-down WebKitGTK view is the least
            // reliable place to send a message from; tao reports the destroy
            // whether or not the page got a chance to run anything.
            if let tauri::RunEvent::WindowEvent {
                label,
                event: tauri::WindowEvent::Destroyed,
                ..
            } = &event
            {
                if window::is_tile_window_label(label) {
                    use tauri::Emitter;
                    let _ = app_handle.emit(window::TILE_WINDOW_CLOSED_EVENT, label.clone());
                }
            }

            // Flush pending spans before the process goes away. The batch
            // exporter holds them in memory, and the last batch is usually the
            // interesting one — whatever happened right before the user quit.
            // No-op without the tracing feature.
            if let tauri::RunEvent::Exit = &event {
                telemetry::shutdown();
            }

            let _ = event;
        });
}
